name: autofix.ci

on:
  pull_request:

permissions:
  contents: read 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Node for JS formatting
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Frontend Dependencies
        run: |
          cd cur8t-web
          pnpm install

      # Setup Python for Python formatting
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python formatters
        run: |
          pip install black isort

      - name: Format Frontend Code
        run: |
          cd cur8t-web
          pnpm run format || true  # ignore non-zero exit codes

      - name: Format Python Code
        run: |
          cd agents-api && black . && isort .
          cd ../extension-api && black . && isort .

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
